### ISSUE TITLE
fatal error: mujoco_ros/util.h: No such file or directory

### ISSUE THREAD

**Issue by rucha6198** [DavidPL1/franka_ros_mujoco#3]
When I try to build the franka_mujoco package, I get the following error:

franka_hw_mujoco.cpp:59:10: fatal error: mujoco_ros/util.h: No such file or directory
   59 | #include <mujoco_ros/util.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.

franka_mujoco/joint.h:60:10: fatal error: mujoco_ros/mujoco_env.h: No such file or directory
   60 | #include <mujoco_ros/mujoco_env.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/franka_hw_sim_mujoco.dir/build.make:63: CMakeFiles/franka_hw_sim_mujoco.dir/src/franka_hw_mujoco.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/franka_hw_sim_mujoco.dir/build.make:102: CMakeFiles/franka_hw_sim_mujoco.dir/src/controller_verifier.cpp.o] Error 1

I do not see a mujoco_env.h file in this repository. Could someone please help me out to solve this error? Thank you.

**Comment by DavidPL1** [comment]
This package requires mujoco_ros (which you can find [here](https://github.com/ubi-agni/mujoco_ros_pkgs)) as it is used to enable running the franka ROS controllers as plugins in the ROS wrapped MuJoCo simulator.

If you were not aware that this package is a plugin for mujoco_ros, are you sure this is the correct package for your use case? How are intending to use it?

**Comment by DavidPL1** [comment]
Can you please provide more information on how you are trying to build this package?

**Comment by rucha6198** [comment]
Thank you for your response. I am sorry I am new to Mujoco so I got a bit confused. So basically I want to create a Hardware interface for the Franka Emika Panda in Mujoco. I am using 'catkin build' to build the package.

**Comment by DavidPL1** [comment]
No worries. So you intend to use ROS.

Make sure to follow the build instructions listed here: https://github.com/ubi-agni/mujoco_ros_pkgs?tab=readme-ov-file#build-instructions

Alternatively, follow the instructions on [this README](https://github.com/ubi-agni/mujoco_ros_demos/tree/noetic-devel/panda_ros_control) in the demo repo.

Let me know if this works

**Comment by rucha6198** [comment]
Yes, I want to use ROS. Thank you so much for providing the resources. I will follow it and get back to you once I have something. Thanks!

**Comment by rucha6198** [comment]
It works fine now. I was not using a different version of Mujoco. Mujoco-2.3.7 is compatible with the package and seems to work fine. Thank you for your help @DavidPL1

**Comment by DavidPL1** [comment]
You're welcome.
Glad to hear it works!
