### ISSUE TITLE
Issue in Wrench Visualization 

### ISSUE THREAD

**Issue by Ekanshh** [DavidPL1/franka_ros_mujoco#6]
### **Description**:

Thanks for the great work on this repo! 💯

I’m working on a project where I need to **visualize interaction forces at the end-effector** during a door interaction task. Using the `cartesian_impedance_example_controller`, I command the robot to grasp the door handle, rotate it by moving in the -z direction, and then open the door by moving in the -x direction. 

### **Issue**:
The door interaction works, but the wrench visualization from `/franka_state_controller/F_ext` shows the vectors in an unexpected direction. I was expecting it to align with the direction of interaction. Am I missing something?

Here's a video showing the issue:  

[issue_in_door_interaction_task.webm](https://github.com/user-attachments/assets/9f196c2b-cb64-48f3-ad48-3d596ae2372d)

Any guidance would be greatly appreciated! :)

**Comment by DavidPL1** [comment]
Maybe the reference frame is incorrect. However, as far as I remember the FT signal is computed somewhere by franka_ros from the joint feedback.

Can you test a simple setup in Gazebo with the Panda to compare the FT signal? This would be helpful to track the error down to either this package or franka_ros.

**Comment by Ekanshh** [comment]
Sure. I will try to test a simple setup in Gazebo sometime this week and keep you updated.

**Comment by Ekanshh** [comment]
**@DavidPL1 Here's an update:**

- I ran a basic example using `franka_ros` and `Gazebo` with the following command:

```bash
roslaunch franka_gazebo panda.launch x:=-0.5 \
    world:=$(rospack find franka_gazebo)/world/stone.sdf \
    controller:=cartesian_impedance_example_controller \
    rviz:=true
```

- The wrench visualizations appear to be working fine in this case. You can check out the video below to see the results:

[wrench_visualization_franka_ros_gz.webm](https://github.com/user-attachments/assets/0e918c78-0fde-47a7-a76e-ce3f273f7f37)

- Given that everything seems to be functioning correctly here, I now suspect that the issue might be within this package rather than `franka_ros`. What are your thoughts on this?

**Comment by DavidPL1** [comment]
Thanks for checking, must be a problem in the mujoco port then.
Right now I'm trying to compare the `franka_states` message in both gazebo and mujoco to get an idea of where things break.

**Comment by Ekanshh** [comment]
This issue in `franka_ros` might be relevant: https://github.com/frankaemika/franka_ros/issues/197

**Comment by DavidPL1** [comment]
The changes from the PR mentioned in the issue were already integrated.

But I think I got it now.
Apparently Gazebo uses the opposite sign when reading joint efforts compared to MuJoCo, i.e. forces applied from the joint vs. forces applied to the joint.

This lead to joint effort and gravity acting on the joint adding up instead of canceling out when computing the external torque `tau_ext = joint->effort - joint->command + joint->gravity`

f47d5ae should fix this, at least with the default model and cartesian impedance control the FT visualization looked reasonable. Please checkout the fix branch and confirm that values now look as expected.

**Comment by Ekanshh** [comment]
Thanks for debugging this issue @DavidPL1! :100: 

I’ll test the fix branch today on my use case and keep you updated. :clinking_glasses:

**Comment by Ekanshh** [comment]
@DavidPL1 FYI, I'm still working on it. I think I need some more time. I will let you know asap.

**Comment by Ekanshh** [comment]
Hi @DavidPL1,

I’ve tested the fix branch and would like your opinion on a couple of points:

1. **FT Visualization**: The FT visualization appears correct until the grasping phase. However, after grasping, the forces seem to add up again, leading to large vector readings when rotating the handle and moving the door.  

2.  **Force Vector Direction**: I believe the force vector should align with the direction in which the robot is trying to exert force. Specifically:
   - When rotating the handle, the force vector should be approximately in the -z direction (indicating movement in -z from the grasp pose).
   - When opening the door, the force vector should be approximately in the -x direction (indicating movement in -x from the door handle opening pose).

I’d appreciate your insights on these observations. Here’s a video demonstrating the issue: 

[output.webm](https://github.com/user-attachments/assets/32fbec46-94b2-4ff5-aac7-868871785781)

Thank you! 🍻

**Comment by DavidPL1** [comment]
In my opinion the vector direction looks plausible.

> 2. **Force Vector Direction**: I believe the force vector should align with the direction in which the robot is trying to exert force. Specifically:
> 
> 
>  * When rotating the handle, the force vector should be approximately in the -z direction (indicating movement in -z from the grasp pose).

It shows the direction of resisting forces w.r.t the robots movement, in this case the door handle resisting to be pressed downward plus the torque resulting from the distance of the contact point to the angle of rotation on the handle acting as a lever.
  
>  * When opening the door, the force vector should be approximately in the -x direction (indicating movement in -x from the door handle opening pose).

When opening the door, the force of the door resisting to be opened adds up to the upward vector.

I'm not sure though that the magnitude of the vector is correct. This could result from a high stiffness of the door handle joint. You could double check by manually calculating approximated expected values.

**Comment by Ekanshh** [comment]
Thanks, @DavidPL1, for your reply. Sorry, it took me some time to get back to you.

I think you're right; my initial understanding of the force in F_ext was likely incorrect.

Following your suggestion, I manually calculated the expected force vector, and its magnitude is reasonably close to that in F_ext.

ATM I don’t have any further questions on this, and the fix seems to be working as expected. You can close the issue and merge the fix branch. :rocket:

**Comment by DavidPL1** [comment]
Thanks for your feedback and for verifying the values.
Good luck with your project!
